### ISSUE TITLE
数据动态改变后  .scroll-bar 节点高度没有重新计算

### ISSUE THREAD

**Issue by SKYNETIGER** [wensiyuanseven/lite-virtual-list#9]
当列表数据动态删除后， .scroll-bar 节点高度没有变化  导致底部留白

**Comment by wensiyuanseven** [comment]
用`vm.$delete()`试试

**Comment by SKYNETIGER** [comment]
> 用`vm.$delete()`试试
多谢回复
我刚才试了下   貌似 还是不行
![image](https://user-images.githubusercontent.com/23398217/104670856-9922ef80-5717-11eb-8a4d-d8b7f44107fb.png)
![image](https://user-images.githubusercontent.com/23398217/104670935-beaff900-5717-11eb-9994-e39251a44f42.png)

**Comment by wensiyuanseven** [comment]
文档已更新，您需要把库升级到`0.1.6`版本。
向组件传入需要删除的item的id值,组件内部会删除item,并且重新计算高度值。
当然对于高度固定的item,您可以在外部直接用`this.data.splice(index,1)`,也能删除。
这有份示例，您可以看一下 
https://wensiyuanseven.github.io/lite-virtual-list/example/deleteItem.html

**Comment by wensiyuanseven** [comment]
> > 用`vm.$delete()`试试
> > 多谢回复
> > 我刚才试了下   貌似 还是不行
> > ![image](https://user-images.githubusercontent.com/23398217/104670856-9922ef80-5717-11eb-8a4d-d8b7f44107fb.png)
> > ![image](https://user-images.githubusercontent.com/23398217/104670935-beaff900-5717-11eb-9994-e39251a44f42.png)

文档已更新，您需要把库升级到0.1.6版本。
向组件传入需要删除的item的id值,组件内部会动态删除此项,并且重新计算高度值。
当然对于高度固定的item,您可以在外部直接用this.data.splice(index,1),也可。
这有份示例，您可以看一下
https://wensiyuanseven.github.io/lite-virtual-list/example/deleteItem.html

**Comment by SKYNETIGER** [comment]
> > > 用`vm.$delete()`试试
> > > 多谢回复
> > > 我刚才试了下   貌似 还是不行
> > > ![image](https://user-images.githubusercontent.com/23398217/104670856-9922ef80-5717-11eb-8a4d-d8b7f44107fb.png)
> > > ![image](https://user-images.githubusercontent.com/23398217/104670935-beaff900-5717-11eb-9994-e39251a44f42.png)
> 
> 文档已更新，您需要把库升级到0.1.6版本。
> 向组件传入需要删除的item的id值,组件内部会动态删除此项,并且重新计算高度值。
> 当然对于高度固定的item,您可以在外部直接用this.data.splice(index,1),也可。
> 这有份示例，您可以看一下
> https://wensiyuanseven.github.io/lite-virtual-list/example/deleteItem.html

ok, 再次感谢
